name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 2

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18.17.1'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Library typecheck
        run: yarn type-check

      - name: Build
        run: yarn build

      - name: Build Development
        run: yarn build:development

      - name: Test
        run: yarn test

      - name: Install dependencies
        working-directory: examples/
        run: yarn --frozen-lockfile

      - name: Build examples
        working-directory: examples/
        run: yarn build
