name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Library typecheck
        run: yarn type-check

      - name: Build
        run: yarn build

      - name: Build Development
        run: yarn build:development

      - name: Test
        run: yarn test

      - name: Install dependencies
        working-directory: examples/
        run: yarn --frozen-lockfile

      - name: Build examples
        working-directory: examples/
        run: yarn build
